config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:new, :create, :edit, :index]
  end

  resources :songs, only: [:show, :update]

  resources :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs

  def sorted_songs
    songs.order('title ASC')
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistsHelper
  before_action :find_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :find_playlist, only: [:show, :edit]
  before_action :get_all_songs, only: [:new, :edit]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    redirect_to @playlist
  end

  def show
  end

  def edit
  end

  def update
    @playlist = Playlist.update(playlist_params)
    redirect_to @playlist
  end

private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end

  def find_playlist
    @playlist = Playlist.find(params[:id])
  end

  def get_all_songs
    @songs = Song.all
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_artist, only: [:new, :create, :index]
  before_action :find_song, only: [:show, :edit, :update]

  def index
    @songs = Song.all
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
      if @song.save
        redirect_to song_path(@song)
      else
        render :new
      end
  end

  def show
  end

  def edit
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end

  def find_artist
    @artist = Artist.find(params[:artist_id])
  end

  def find_song
    @song = Song.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def find_artist
    @artist = Artist.find(params[:id])
  end
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %>'s info</h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>All the artists</h1>

<% @artists.each do |artist| %>
<%= link_to artist.name, artist_path(artist) %>
<% end %>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>Create a new artist</h1>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %>'s info</h1>

<%= image_tag @artist.image_path %>

<%= link_to "Edit", edit_artist_path(@artist) %>
<%= link_to "Delete", artist_path(@artist), method: :delete %>
<%= link_to "New song", new_artist_song_path(@artist) %>
<%= link_to "View Songs", artist_songs_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.text_field :name %>

  <% @songs.each do |song| -%>
    <div>
      <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit <%= @playlist.name %>'s info</h1>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h1>All of your playlists</h1>

<% @playlists.each do |playlist| %>
<%= link_to playlist.name, playlist_path(playlist) %>
<% end %>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<h1>Create a new Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %>'s Songs</h1>

<ul>
  <% @playlist.songs.each do |song| %>
    <li><%= link_to song.title, song_path(song) %></li>
  <% end %>
</ul>

<%= link_to "Edit", edit_playlist_path(@playlist) %>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>
  <% if @song.errors.any? %>
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit <%= @song.title %>'s info</h1>

<%= render partial: "form" %>

app/views/songs/index.html.erb
<h1>All of <%= @artist.name %>'s Songs</h1>

<% @artist.sorted_songs.each do |song| %>
<%= song.title %>
<% end %>

app/views/songs/new.html.erb
<p>Add a new song for <%= @artist.name %></p>

<%= render partial: "form" %>

app/views/songs/show.html.erb
<h1><%= @song.title %>'s info</h1>

<%= link_to @song.artist.name, artist_path(@song.artist) %>
<%= link_to "Edit", edit_artist_song_path(@song) %>